// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted_follow AS(
    INSERT INTO feed_follows(user_id,feed_id)
    VALUES($1, $2)
    ON CONFLICT (user_id, feed_id)
    DO UPDATE SET user_id = feed_follows.user_id
    RETURNING id, created_at, updated_at, user_id, feed_id
)
SELECT ff.id, ff.user_id, u.name AS user_name, ff.feed_id, f.name AS feed_name, f.url AS feed_url  
FROM inserted_follow ff
JOIN users u ON u.id = ff.user_id
JOIN feeds f ON f.id = ff.feed_id
`

type CreateFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateFeedFollowRow struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	UserName string
	FeedID   uuid.UUID
	FeedName string
	FeedUrl  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.UserID, arg.FeedID)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.FeedID,
		&i.FeedName,
		&i.FeedUrl,
	)
	return i, err
}

const deleteFeedByURL = `-- name: DeleteFeedByURL :exec
DELETE FROM feed_follows ff
USING feeds f
WHERE ff.feed_id = f.id
    AND ff.user_id = $1
    AND f.url = $2
`

type DeleteFeedByURLParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) DeleteFeedByURL(ctx context.Context, arg DeleteFeedByURLParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedByURL, arg.UserID, arg.Url)
	return err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT u.name AS feed_of, f.name AS feed_name, f.url AS feed_url, feed_id 
FROM feed_follows ff
JOIN feeds f ON f.id = ff.feed_id
JOIN users u ON u.id = f.user_id
WHERE ff.user_id = $1
`

type GetFeedFollowsForUserRow struct {
	FeedOf   string
	FeedName string
	FeedUrl  string
	FeedID   uuid.UUID
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(
			&i.FeedOf,
			&i.FeedName,
			&i.FeedUrl,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
