// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const browse = `-- name: Browse :many
SELECT id, created_at, updated_at, title, url, description, published_at, feed_id FROM posts
ORDER BY published_at DESC NULLS LAST
LIMIT $1
`

func (q *Queries) Browse(ctx context.Context, limit int32) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, browse, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createPost = `-- name: CreatePost :exec
INSERT INTO posts(title,url,description,published_at,feed_id)
VALUES($1, $2, $3, $4, $5)
ON CONFLICT (url) DO NOTHING
`

type CreatePostParams struct {
	Title       string
	Url         sql.NullString
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT title,description,published_at FROM posts
WHERE feed_id = $1
ORDER BY published_at DESC NULLS LAST
LIMIT 2
`

type GetPostsForUserRow struct {
	Title       string
	Description sql.NullString
	PublishedAt sql.NullTime
}

func (q *Queries) GetPostsForUser(ctx context.Context, feedID uuid.UUID) ([]GetPostsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostsForUser, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(&i.Title, &i.Description, &i.PublishedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
